Seed with existing locales
mozilla-l10n/firefoxtv-l10n pull request #1
Opened 2018-02-12 20:06 UTC by boek

Generated `app.po` files based on the `strings.xml` files in the Firefox-TV repo

2018-02-13 00:43 UTC, Delphine requested changes
So I think this generally looks good and makes sense. Just a few comments:
* In many cases, the comments still call out "Focus" while we're dealing with Firefox for Fire TV here. Probably better to update those to avoid confusion when new locales will be added (I'm mainly concerned that most localizers don't necessarily know the product is based off Focus)
* Some comments call out Android: probably better to avoid that reference to avoid confusion too
* Note to myself: I'll have to ask the localizers from the locales that we did machine translation for Turbo Mode strings, to check and update those translations if needed
* Once we have a language switcher, we should remember to import strings from all other locales that have a Focus Android localization
* Waiting to hear back from Barbara about if we should enable en-GB on Pontoon or not this time around (that does not block us on this though since they don't have any localization to import from Focus Android).
I think that's it! thanks Jeff

2018-02-13 00:43 UTC, Delphine commented on locales/templates/app.pot
> +#. Focus video strings
Comment needs to be updated with "Firefox TV" to avoid confusion

2018-02-13 00:43 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Hollywood Reporter"
Maybe add comment that this isn't supposed to get translated since it's an American magazine's name (and translators don't necessarily know that)?

2018-02-13 00:43 UTC, Delphine commented on locales/templates/app.pot
> +#. Appended by save_robotranslations.py
This comment doesn't make sense to me - probably better to update it (or remove)

2018-02-13 00:43 UTC, Delphine commented on locales/templates/app.pot
> +#. Notification action to open Focus and resume the current browsing session.
Update comment with "Firefox TV" instead of "Focus"

2018-02-13 00:43 UTC, Delphine commented on locales/templates/app.pot
> +#. Notification action to open Focus and resume the current browsing session.
(there are many occurrences throughout comments so stopped calling them out)

2018-02-13 06:29 UTC, flodolo commented
> Note to myself: I'll have to ask the localizers from the locales that we did machine translation for Turbo Mode strings, to check and update those translations if needed

If you provide the list of locales and strings, I can work on top of the PR to mark those strings as fuzzy before we enable Pontoon, so they will have to look at them.

2018-02-13 16:49 UTC, Delphine commented
@flodolo: oh cool, yeah that's super helpful! 
The locales concerned here are: de, es-ES, fr, it, ja and zh-CN (so all except pt-BR).

For the record, we also had those strings machine translated for Korean, Russian and Hindi - but we're not dealing with those in this PR.

Side-note, Barbara confirmed in [bug 1436856](https://bugzilla.mozilla.org/show_bug.cgi?id=1436856) that we'd wait for the locale switcher to add en-GB

2018-02-13 17:02 UTC, flodolo commented
> The locales concerned here are: de, es-ES, fr, it, ja and zh-CN (so all except pt-BR).

We did manual translation for fr and it, didn't we? I can do it once we've merged this.

2018-02-13 17:12 UTC, Delphine commented
> We did manual translation for fr and it, didn't we? I can do it once we've merged this.
Correct! those all the only two. I'll update my comment to avoid any possible future confusion

2018-02-14 00:29 UTC, Delphine requested changes
Thanks for the update. I think we're almost there!
Some comments:
* we agreed with Jeff not to take out the Android references in the end, as these remain useful and shouldn't lead to too much confusion for localizers
* on second thoughts, we should probably add comments to the Home tile strings. The only one that isn't a brand is "video search" from the google video search tile. I'm afraid that, although some of these brands are globally famous and recognized, localizers might not get *all* of them
I think that should be it! thanks

2018-02-14 04:30 UTC, boek commented
Ready for a final review 🙌

2018-02-14 17:53 UTC, boek commented
@Delphine @flodolo. I'm not able to update the PR to re-request review. So just pinging you here :)

2018-02-14 17:54 UTC, flodolo commented
Yep, @Delphine is already looking into it

2018-02-14 17:57 UTC, Delphine approved these changes
Looks good from here :) Thanks Jeff!

2018-02-14 17:57 UTC, merged